version: 2
jobs:
  build:
    docker:
      - image: cloudpipelines/pipeline-base
    environment:
      MAVEN_OPTS: "-Xms64m -Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs=-Xms64m -Xmx250m -XX:+HeapDumpOnOutOfMemoryError"
      TERM: dumb
    branches:
      ignore:
        - gh-pages # list of branches to ignore
    resource_class: large
    steps:
      - setup_remote_docker
      - checkout
      - restore_cache:
          key: sc-contract-{{ .Branch }}
      - run:
          name: "Download dependencies"
          command: ./scripts/downloadDependencies.sh
      - save_cache:
          key: sc-contract-{{ .Branch }}
          paths:
            - ~/.m2
            - ~/.gradle
      - run:
          name: "Adding daemon entries for Gradle"
          command: touch ~/.gradle/gradle.properties && echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
      - run:
          name: "Clearing caches"
          command: rm -rf ~/.m2/repository/org/springframework/cloud/contract && rm -rf ~/.m2/repository/com/example
      - run:
          name: "Running build"
          command: ./mvnw -s .settings.xml clean install -U -Pdocs,fast,integration -nsu --batch-mode -Dmaven.test.redirectTestOutputToFile=true -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      - run:
          name: "Aggregate test results"
          when: always
          command: |
            mkdir -p $CIRCLE_TEST_REPORTS/junit/
            find . -type f -regex ".*/target/.*-reports/.*" -exec cp {} $CIRCLE_TEST_REPORTS/junit/ \;
            find . -type f -regex ".*/build/test-results/.*" -exec cp {} $CIRCLE_TEST_REPORTS/junit/ \;
            bash <(curl -s https://codecov.io/bash)
      - store_artifacts:
          path: /junit/
          destination: artifacts
      - store_test_results:
          path: /junit/
          destination: testartifacts
notify:
  webhooks:
    # A list of hook hashes, containing the url field
    # gitter hook
    - url: https://webhooks.gitter.im/e/ece0ece9a76a5af2aa91
